import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StoreWrapper } from '@/modules/wrapper'
import { store } from '@/stores/store'
import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <StoreWrapper store={store}>
                <body className={inter.className}>{children}</body>
            </StoreWrapper>
        </html>
    )
}
